package protodescriptorset

const typeSignatureBool = "bool"
const typeSignatureInt32 = "int32"
const typeSignatureInt64 = "int64"
const typeSignatureUint32 = "uint32"
const typeSignatureUint64 = "uint64"
const typeSignatureSint32 = "sint32"
const typeSignatureSint64 = "sint64"
const typeSignatureFixed32 = "fixed32"
const typeSignatureFixed64 = "fixed64"
const typeSignatureSfixed32 = "sfixed32"
const typeSignatureSfixed64 = "sfixed64"
const typeSignatureFloat = "float"
const typeSignatureDouble = "double"
const typeSignatureString = "string"
const typeSignatureBytes = "bytes"
const typeSignatureUnknown = "unknown"
